#此文件以UTF-8的格式保存
spring
	profiles :
	active :
	- dev :
---
spring
	profiles : dev #开发环境配置
	application ：
		name : microservice-configserver10001-dev
---
spring
	profiles : test #测试环境配置
	application ：
		name : microservice-configserver10001-test
